"use strict";

const Loc = (() => {
    let lang = localStorage.getItem("fc-lang") === "en" ? "en" : "ru";
    const dict = {
        ru: {
            tap: "нажми",
            becomeLegend: "Стань легендой",
            modeLead: "Тренируйся. Играй матчи. Переходи в топ.",
            continue: "▶ ПРОДОЛЖИТЬ",
            continueMeta: "Сохранённая карьера",
            modePlayer: "👤 ИГРОК",
            modePlayerSub: "Карьера футболиста: тренировки, матчи, трансферы",
            modeClub: "🏟️ КЛУБ",
            modeClubSub: "Управляй командой: лиги, состав, бюджет",
            modeBattle: "🌐 ОНЛАЙН БАТЛ",
            modeBattleSub: "Бой карточками: случайный соперник или код друга. Это не живой сервер",
            modeAuction: "🏆 АУКЦИОН ЧМ",
            modeAuctionSub: "11 слотов 4-3-3 · ЧМ 1994–2026 · 1 перекрутка. Не связано с FC3",
            code: "Код",
            promoHint: "Код даёт +100 000 $ в эту карьеру. Один раз.",
            records: "Рекорды",
            backModes: "← К режимам",
            newPlayer: "Новый игрок",
            newClub: "Новый клуб",
            createPlayer: "Создай своего футболиста",
            createClub: "Создай свой клуб",
            startCareer: "Начать карьеру",
            startClub: "Начать клуб",
            nation: "Национальность",
            avatar: "Аватар",
            menu: "← Меню",
            myCareer: "Моя карьера",
            myClub: "Мой клуб",
            labelNation: "Нация",
            labelCountry: "Страна",
            labelPos: "Позиция",
            labelCity: "Город",
            labelClub: "Клуб",
            labelLeague: "Лига",
            ageWeek: "Возраст",
            week: "Неделя",
            energy: "Энергия",
            fame: "РЕП",
            tabHome: "Главная",
            tabTrain: "Треня",
            tabMatch: "Матч",
            tabClubs: "Клубы",
            tabClub: "Клуб",
            tabMore: "Ещё",
            tabBank: "Банк",
            bankTitle: "Банк",
            bankCash: "На руках",
            bankSave: "На вкладе",
            bankDebt: "Долг",
            bankPh: "Сумма, пусто = всё",
            bankAll: "Всё",
            bankIn: "Положить",
            bankOut: "Снять",
            bankBorrow: "Взять кредит",
            bankRepay: "Погасить",
            bankSaveHint: "Лучший вклад — длинный, +18%.",
            bankBestSave: "Лучший вклад",
            bankDebtOpen: "Окно долга",
            bankHint: "Малый и обычный без залога. Большой кредит просит фирму: лучше фирма — больше сумма и ниже процент.",
            bankPickSave: "Лучший вклад — длинный, +18%.",
            bankPickLoan: "Малый и обычный без залога. Большой кредит просит фирму.",
            bankBigNeed: "Большой кредит. Просят залог.",
            bankPledgeFree: "не просят",
            bankOffer_small: "Малый до {cap}. +{rate}%. Без залога",
            bankOffer_mid: "Обычный до {cap}. +{rate}%. Без залога",
            bankPledgeLabel: "Залог",
            bankNoPledge: "нет",
            bankNoFirm: "Нет фирмы — большой кредит не дадут.",
            bankNeedFirm: "Эта фирма не твоя. Залог не примут.",
            bankPledged: "в залоге",
            bankGrade1: "слабая",
            bankGrade2: "обычная",
            bankGrade3: "хорошая",
            bankGrade4: "сильная",
            bankGrade5: "лучшая",
            bankLoanBtn: "Залог {name} · {grade} · до {cap} · +{rate}%",
            bankOfferCopy: "Копилка +4%. Снять сразу",
            bankOfferSeason: "Сезон +12%. Нельзя снять 1 сезон",
            bankOfferLong: "Лучший вклад. Длинный +18%. Нельзя снять 3 сезона",
            bankOfferShort: "Короткий до $800. +6%. Лучший",
            bankOfferMid: "Обычный до $2500. +14%",
            bankOfferBig: "Большой до $7000. +25%",
            bankSave_copy: "Копилка +4%",
            bankSave_season: "Сезон +12%",
            bankSave_long: "Длинный +18%",
            bankLoan_small: "Малый +8%",
            bankLoan_mid: "Обычный +14%",
            bankLoan_big: "Большой",
            bankLocked: "Вклад закрыт ещё {n} сез.",
            bankOther: "Сначала сними старый вклад.",
            bankOtherLoan: "Сначала погаси старый кредит.",
            bankPoor: "Не хватает денег.",
            bankEmpty: "На вкладе пусто.",
            bankNoDebt: "Долга нет.",
            bankNoLoan: "Лимит кредита {n}.",
            logBankIn: "{plan}: положил {n}.",
            logBankOut: "Снял {n}.",
            logBankLoan: "Под залог {plan}: взял {n}.",
            logBankPay: "Погасил {n}.",
            logBankGrow: "{plan}: проценты {n}.",
            logBankDebt: "{plan}: долг вырос на {n}.",
            socOpen: "Соцсеть",
            socBrandName: "PULSE",
            socPlayer: "Игрок",
            socClub: "Клуб",
            socFollowers: "подписчики",
            socFollowers: "подписчики",
            socFollowing: "подписки",
            socPosts: "посты",
            socBioPlayer: "{pos} · {club} · {nation}",
            socBioClub: "{city} · {league}",
            socMatch: "МАТЧ",
            socStat: "СТАТ",
            socNt: "СБОРНАЯ",
            socTrophy: "ТИТУЛ",
            socBrand: "БРЕНД",
            socLife: "ЖИЗНЬ",
            socClubTag: "КЛУБ",
            socGoals: "{n} голов в карьере. Лента это уже видела.",
            socGoalsClub: "{n} голов команды в этом сезоне пути.",
            socCall: "Официально: вызов в сборную {nation}.",
            socBrandPost: "Запустили {name}. Мерч уже в ленте.",
            socLifeLine: "{name} · {pos} · сейчас {club}.",
            socClubLine: "{name} · {city} · {league}.",
            socC1: "Легенда. Не останавливайся.",
            socC2: "Ждём следующий матч.",
            socC3: "Это уже другой уровень.",
            socC4: "Вся лента на тебе.",
            socC5: "Этот пост надо закрепить.",
            socC6: "Смотрю с первого ряда.",
            socC7: "Клуб или игрок — лента уже гудит.",
            socC8: "Сохрани это, потом будет история.",
            socSpam: "ПАПА-КОРОЛЬ!!!",
            socSpamTag: "СПАМ",
            socPublish: "Опубликовать",
            socAd: "Реклама",
            socAdKicker: "ПРОДАЖИ",
            socAdBody: "Новый дроп. Ссылка никуда не ведёт — {link}",
            socAdBank: "Лучший вклад +18% на 3 сезона. pulse.fake/bank",
            socAdDeal: "{brand}. Рекламный договор. pulse.fake/buy",
            socAdFirm: "{name}. Новый дроп. pulse.fake/buy",
            socAdUp: "Продажи выросли. Реклам: {n}",
            socAdReply: "Открыл ссылку pulse.fake/buy. Пустая, но беру.",
            socAdDead: "Ссылка пустая. Никуда не ведёт.",
            socAdNoFirm: "Сначала открой фирму. Без фирмы рекламы нет.",
            socAdSent: "Реклама ушла {name}. Продажи вверх.",
            logAdFriend: "📣 Реклама для {name} · −{pay}",
            logAd: "📣 Реклама · −{pay} · всего {n}",
            retireBtn: "Закончить карьеру",
            retireAsk: "Закончить карьеру? Матчи, треня и батлы закроются.",
            retireKicker: "ФИНИШ",
            retireTitle: "Карьера закрыта",
            retireSub: "Играть больше нельзя.",
            retiredBtn: "Карьера закончена",
            logRetire: "🏁 Карьера закончена. Играть нельзя.",
            logRetired: "Карьера закрыта. На поле уже нельзя.",
            socPlaceholder: "Напиши пост…",
            socNeedText: "Напиши хоть пару слов.",
            socMine: "ПОСТ",
            socLikesTitle: "Лайки",
            socDownsTitle: "Дизлайки",
            socCommentsTitle: "Комментарии",
            socBack: "Лента",
            socWeek: "неделя {n}",
            socMoreLikes: "и ещё {n}",
            socMates: "КЛУБ",
            socSeason: "26/27",
            socStill: "играет",
            socStillTitle: "Ещё играет",
            socStillHint: "Криштиану и Жоау Феликс ещё играют. Оба в Аль-Насре.",
            socMate1: "После тренировки. {club} сегодня злой.",
            socMate2: "Кто в основе на выходных? Я готов.",
            socMate3: "Раздевалка гудит. {club} не отпускает.",
            socMate4: "Ещё круг — и на лёд. Шутка. На газон.",
            socMateA: "{name}: после дерби {club} заслужил эти очки.",
            socMateB: "{pos} {name} смотрит разбор. В основе должен быть злее.",
            socMateC: "{name} про выходные: кто выше по OVR, тот играет.",
            socMateD: "Ночь перед матчем. {name} уже спит, {club} нет.",
            socMateE: "Гол {name} ещё в голове. Так {club} и играет.",
            socMateF: "{name} остался после тренировки. {pos} не отпускает.",
            socMateG: "{club} сегодня тихий. {name} говорит, так и надо.",
            socMateH: "{name} в ленте с газона. {pos}, не с дивана.",
            socMateI: "Новый пост. {name} только с тренировки {club}.",
            socMateJ: "{name}: неделя свежая, {club} уже в ленте.",
            socMateK: "{pos} {name} выложил разбор. Вчерашний матч ещё в голове.",
            socMateL: "{club} шумит. {name} пишет прямо из раздевалки.",
            socMateM: "Сегодня другой текст. {name} не копирует вчерашний пост.",
            socMateN: "{name} про {club}: лайки приходят, когда клуб большой.",
            socMateO: "После игры {name} снова в сети. {pos} не молчит.",
            socMateP: "{name}: если читаешь — ответь. {club} на связи.",
            socFeed: "Лента",
            socSubs: "Подписки",
            socPlan: "Тариф",
            socPlanNoob: "noob · $0 · до 10 реклам",
            socPlanSilver: "silver · $67 · до 67 реклам",
            socPlanGold: "gold · $120 · без лимита",
            socPlanNow: "Сейчас {plan}. Реклам {n}. Каждая −$1.",
            socPlanCap: "Лимит рекламы. Тариф {plan}.",
            socPlanBuy: "Тариф {plan}.",
            socPlanPoor: "Не хватает денег.",
            socAdTired: "Людям надоела реклама. Покупают меньше, репутация вниз.",
            logAdTired: "📣 Реклама надоела · репутация −{hit}",
            socSub: "подписка",
            socSubbed: "подписан",
            socUnsub: "отписаться",
            socSubsN: "Подписок: {n}",
            socSubsEmpty: "Пока ни на кого. Жми «подписка» в ленте или ниже.",
            socWorld: "ИГРОК",
            socFriends: "Друзья",
            socAddFriend: "в друзья",
            socWrite: "написать",
            socFriendN: "Друзей: {n}",
            socNoFriends: "Пока никого. Добавь из ленты или из списка ниже.",
            socAlive: "",
            socAliveShort: "",
            socMatesPick: "Одноклубники",
            socLegends: "Легенды",
            socChatPh: "Написать…",
            socTyping: "печатает…",
            socPing1: "Есть минута?",
            socPing2: "Видел пост.",
            socPing3: "Завтра на поле?",
            socPing4: "Как форма?",
            socPing5: "Напиши, как будет время.",
            socPing6: "Я в сети.",
            socChip1: "Занят. Ем чипсы.",
            socChip2: "Не могу. Чипсы.",
            socChip3: "Всегда занят. Пачка ещё полная.",
            socChip4: "Потом. Сейчас хрустю.",
            socChip5: "Не до разговора. Чипсы.",
            socJoke1: "Вратарь: я всё вижу. Мяч: а я уже в сетке.",
            socJoke2: "Тренер: беги быстрее. Игрок: я легенда, просто медленная.",
            socJoke3: "Судья: зачем рука? Нападающий: это нога, только сверху.",
            socJoke4: "На скамейке теплее. Поэтому запасные всегда в форме.",
            socJoke5: "Гол засчитали. Комментатор молчал. Трибуна сама договорила.",
            socCalc: "{n}",
            socCalcAsk: "Кидай пример. 2+2.",
            socSawHat: "Хет-трик. Я это видел.",
            socSawGoal: "Гол. {score}.",
            socSawWin: "Победа {score}.",
            socSawDraw: "{score}. Жёстко.",
            socSawLoss: "{score}. В следующий раз.",
            socYes: "Да.",
            socGreat: "Отлично.",
            socPingListen: "Давай. Слушаю.",
            socPingPitch: "Тогда завтра.",
            socPingWrite: "Жду.",
            socPingOn: "Я тоже.",
            socFormOk: "Нормально.",
            socYou: "Ты",
            socHi: "Привет.",
            socFan: "Спасибо. Приятно.",
            socHow: "Нормально. А у тебя?",
            socMorning: "Доброе утро.",
            socLuck: "Спасибо. И тебе.",
            socWc: "Да, люблю.",
            socGoat: "Оба, но у него больше голов, золотых мячей и бутс в Лиге чемпионов, и в 2016 году он обогнал Лионеля Месси на рекордное количество очков в «Золотом мяче». У Месси был заметный фол, но карточку за касание рукой не дали.",
            socGoatMe: "Оба, но у меня больше голов, золотых мячей и бутс в Лиге чемпионов, и в 2016 году я обогнал Лионеля Месси на рекордное количество очков в «Золотом мяче». У Месси был заметный фол, но карточку за касание рукой не дали.",
            socOk: "Ок.",
            socPitch: "Ладно. На поле.",
            socAsk: "Обсудим.",
            socThanks: "Не за что.",
            socBye: "Встретимся, расскажу.",
            socGot1: "Понял.",
            socGot2: "Учту.",
            socGot3: "Ясно.",
            socGot4: "Ладно.",
            socGot5: "Встретимся, расскажу.",
            socGot6: "Обсудим.",
            socCopy1: "Хватит копировать.",
            socCopy2: "Опять одно и то же. Надоело.",
            socCopy3: "Я уже ответил. Не повторяй.",
            socTalkMud: "Не понял. Напиши нормально.",
            socMe: "Я {name}. {pos}, {club}, OVR {ovr}.",
            socMeWho: "Я {name}.",
            socMeClub: "Играю за {club}.",
            socMeWas: "Карьеру закончил. Играл за {club}.",
            socMePos: "Моя позиция — {pos}.",
            socMeOvr: "Мой OVR — {ovr}.",
            socCommentPh: "Комментарий…",
            socSend: "Отправить",
            socClear: "Очистить",
            socGibberish: "Пост не зашёл. Мало лайков, репутация и подписки вниз.",
            socGibberishC: "Комментарий не поняли. Репутация и подписки вниз.",
            socFieldKicker: "АЧИВКА",
            socFieldTitle: "ИДИ НА ПОЛЕ",
            socField: "Восемь нормальных постов подряд без матча. Лента закрыта, пока не сыграешь.",
            socFieldLock: "Лента подождёт. Сыграй матч.",
            logSocField: "📱 Ачивка: слишком долго в соцсетях. Иди на поле.",
            body: "Тело",
            bodyOk: "Цел. Травма подсветит зону.",
            stats: "Характеристики",
            training: "Тренировка",
            schedule: "Расписание",
            nextMatch: "Следующий матч",
            matchday: "Игровой день",
            matches: "Матчи",
            wins: "Победы",
            draws: "Ничьи",
            losses: "Поражения",
            goals: "Голы",
            assists: "Ассисты",
            conceded: "Пропущено",
            tackles: "Отборы",
            saves: "Сейвы",
            cleans: "Сухие матчи",
            autosave: "💾 Автосохранение каждые 20 сек",
            noMatches: "Пока нет матчей",
            waitDay: "📅 ЖДИ ИГРОВОЙ ДЕНЬ",
            bribe: "🤫 ПОДКУПИТЬ СУДЬЮ",
            bribeHint: "Подкуп: 30% поможет, 70% штраф. Репутация падает в любом случае.",
            online: "Онлайн",
            onlineBtn: "🌐 ОНЛАЙН БАТЛ",
            onlineHint: "Карточки, не живой матч. −18 энергии. Код друга — единственный настоящий соперник.",
            sideTitle: "Календарь и батл",
            squad: "Состав",
            squadHint: "Своих игроков пока нет. Купи в трансферном окне.",
            market: "Трансферное окно",
            marketHint: "От ЦСКА до легенд Реала. Покупка за $.",
            all: "Все",
            europe: "Европа",
            legends: "Легенды",
            transfers: "🔄 Трансферы",
            leagues: "📈 Лиги",
            firms: "Фирмы",
            firmsHint: "Все фирмы в таблице. Основание только за $. Доход каждую неделю — от репутации и богатства.",
            dealsTitle: "Рекламные договоры",
            dealsHint: "До трёх марок. Деньги каждую неделю. В соцсети реклама крутит лучший вклад и эти бренды. Лучший договор — PMW.",
            dealsPay: "Договоры /нед",
            dealBtn: "{name} · реп {fame} · {cost} · +{pay}/нед{best}",
            dealBest: " · лучший",
            dealOwned: "{name} · твой · {n}",
            dealYours: "Этот договор уже подписан.",
            dealFull: "Хватит. Уже {n} договора.",
            dealFame: "Нужна репутация {n}. Сейчас {now}.",
            dealPoor: "На договор нужно {pay}.",
            dealSigned: "Реклама этой марки пойдёт в соцсеть.",
            logDeal: "Договор {name}. −{pay}.",
            logDealWeek: "Договоры за неделю: {pay}.",
            cashWeek: "Счёт:",
            firmsWeek: "· все фирмы /нед",
            firm: "Фирма",
            price: "Цена",
            perWeek: "/нед",
            promoHintCareer: "+100 000 $ · один раз · эта карьера, не FC3",
            auction: "Аукцион ЧМ",
            auctionHint: "Собери 4-3-3 из случайных игроков ЧМ 1994–2026. Отдельный режим, карьеру не ломает.",
            openAuction: "🏆 ОТКРЫТЬ АУКЦИОН",
            history: "История",
            restart: "Заново",
            dockMatch: "⚽ Матч",
            dockBattle: "🌐 Батл",
            dockRest: "😴 Отдых",
            dockMenu: "← Меню",
            auctionHow: "Жми ИГРОК — один легенда за раз, строго в свою позицию (Неймар только LW). 1 перекрутка той же позиции. ЗАНОВО — новый состав.",
            auctionEmpty: "Пусто · перекруток: 1",
            player: "ИГРОК",
            reset: "ЗАНОВО",
            tapCode: "введи код",
            namePlayer: "Имя футболиста",
            nameClub: "Название клуба",
            cityPh: "Город (например Москва)",
            brandPh: "название фирмы (необязательно)",
            friendCode: "Код друга",
            yourCode: "Твой код — друг играет против твоей карточки",
            playCode: "🎮 ИГРАТЬ ПО КОДУ",
            fight: "⚽ В БОЙ",
            cancel: "ОТМЕНА",
            arena: "ОНЛАЙН АРЕНА",
            search: "Поиск соперника",
            scan: "сканируем лобби…",
            sound: "Звук",
            style: "Стиль",
            styleTitle: "Стиль",
            stylePremium: "Премиум",
            stylePlain: "Обычный",
            styleArcade: "Аркада",
            styleBoard: "Табло",
            inf: "ушиб",
            sprain: "растяжение",
            muscle: "мышца",
            break: "перелом",
            inj_bruise: "ушиб",
            inj_sprain: "растяжение",
            inj_muscle: "мышца",
            inj_break: "перелом",
            part_head: "голова",
            part_shoulder: "плечо",
            part_arm: "рука",
            part_ribs: "рёбра",
            part_back: "спина",
            part_groin: "пах",
            part_hamstring: "бедро",
            part_knee: "колено",
            part_calf: "икра",
            part_ankle: "лодыжка",
            firm_wear: "одежда",
            firm_boots: "бутсы",
            firm_drink: "напиток",
            firm_perfume: "парфюм",
            firm_eatery: "ресторан",
            firm_agency: "агентство",
            yours: "твоя",
            need: "надо",
            buy: "купить",
            needRep: "реп",
            ward: "ЛАЗАРЕТ",
            streak: "СЕРИЯ",
            now: "СЕЙЧАС",
            next: "ДАЛЬШЕ",
            skip: "ПРОПУСТИТЬ",
            skipDock: "🤕 Пропуск",
            lowEnergy: "⚡ МАЛО ЭНЕРГИИ",
            energyDock: "⚡ Энергия",
            playVs: "⚽ ИГРАТЬ · vs",
            inWeeks: "📅 ЧЕРЕЗ {w} {unit}",
            week1: "НЕДЕЛЮ",
            weeks: "НЕД.",
            weeksShort: "нед",
            vs: "vs",
            weekWord: "Неделя",
            homeVs: "дом vs ",
            awayAt: "выезд @ ",
            nowGrid: "сейчас",
            pens: "пен.",
            fame_legend: "легенда",
            fame_star: "звезда",
            fame_respect: "уважение",
            fame_ok: "норма",
            fame_stain: "пятно",
            fame_scandal: "скандал",
            recRep: "Реп",
            recGoals: "Голы",
            recClub: "Клуб",
            intact: "Цел. Травма подсветит зону.",
            hurt: "Повреждено",
            rest: "😴 ВОССТАНОВИТЬСЯ +50 · бесплатно",
            restWait: "⏳ Подожди {n} сек",
            restDock: "😴 Отдых",
            restDockWait: "⏳ {n}с",
            restFast: "⚡ 100% ЗА $100 · 1 сек",
            restNeed: "⚡ НУЖНО $100",
            trainHint: "Тренировка: −16 энергии, +1 неделя. Отдых +50 бесплатно (12 сек) или 100% за деньги (1 сек).",
            trainHintClub: "Тренировка состава: −16 энергии. Отдых +50 бесплатно (12 сек) или 100% за деньги (1 сек).",
            trainHintGk: "Вратарские тренировки. Отдых +50 бесплатно (12 сек) или 100% за деньги (1 сек).",
            trainHintCb: "Тренировки ЦЗ. Отдых +50 бесплатно (12 сек) или 100% за деньги (1 сек).",
            fixtureDue: "Сегодня игра. Ничья → серия пенальти. Лишний матч сыграть нельзя.",
            fixtureWait: "Матч раз в {n} недели. Ещё {w} {unit} — тренируйся до игрового дня.",
            unit1: "неделя",
            unitN: "нед.",
            hurtHint: "Ты в лазарете. Можно пропустить игровой день или лечить отдыхом.",
            hurtHintClub: "Лидер в лазарете. Можно пропустить игровой день или лечить отдыхом.",
            hookHurtDue: "Травма. Пропусти матч или лечись отдыхом.",
            hookHurtWait: "{label} Отдых двигает неделю.",
            hookStreakDue: "Не рви серию. Матч сейчас.",
            hookStreakWait: "Серия жива. Ещё {w} {unit} — и снова в бой.",
            hookNowLow: "Отдохни и сразу в матч. Не уходи.",
            hookNow: "Игровой день. Один матч — и ты ещё ближе.",
            hookTomorrow: "Завтра игровой день. Прокачайся до свистка.",
            hookWait: "Ещё {w} нед. до матча. Тренируйся — будет легче забить.",
            pos_ST: "ST — Нападающий",
            pos_LW: "LW — Левый вингер",
            pos_RW: "RW — Правый вингер",
            pos_CAM: "CAM — Атакующий полузащитник",
            pos_CM: "CM — Полузащитник",
            pos_CDM: "CDM — Опорный полузащитник",
            pos_CB: "CB — Центральный защитник",
            pos_LB: "LB — Левый защитник",
            pos_RB: "RB — Правый защитник",
            pos_GK: "GK — Вратарь",
            lbl_pace: "⚡ Скорость",
            lbl_shooting: "🎯 Удар",
            lbl_passing: "🅰️ Пас",
            lbl_dribbling: "🕺 Дриблинг",
            lbl_defending: "🛡️ Защита",
            lbl_physical: "💪 Физика",
            lbl_diving: "🧤 Прыжок",
            lbl_handling: "✋ Руки",
            lbl_kicking: "🦶 Вынос",
            lbl_reflexes: "⚡ Реакция",
            lbl_speed: "🏃 Скорость",
            lbl_positioning: "📍 Позиция",
            lbl_marking: "🛡️ Опека",
            lbl_tackling: "🦵 Отбор",
            lbl_heading: "🦅 Голова",
            lbl_strength: "💪 Сила",
            lbl_jumping: "🦘 Прыжок",
            club_pace: "⚡ Темп",
            club_shooting: "🎯 Атака",
            club_passing: "🅰️ Пас",
            club_dribbling: "🕺 Техника",
            club_defending: "🛡️ Оборона",
            club_physical: "💪 Физика",
            weekOf: "неделя",
            bribeAfter: "🤫 ПОДКУП ПОСЛЕ ИГРОВОГО ДНЯ",
            bribeNeed: "🤫 НУЖНО ",
            bribePay: "🤫 ПОДКУП · ",
            skipShort: "Пропуск",
            energyShort: "⚡ Энергия",
            matchShort: "⚽ Матч",
            wk: "нед",
            weekN: "Неделя",
            hintClubInj: "Лидер в лазарете. Можно пропустить игровой день или лечить отдыхом.",
            hintInj: "Ты в лазарете. Можно пропустить игровой день или лечить отдыхом.",
            hintDue: "Сегодня игра. Ничья → серия пенальти. Лишний матч сыграть нельзя.",
            hintWait: "Матч раз в {every} недели. Ещё {w} {unit} — тренируйся до игрового дня.",
            unit1u: "НЕДЕЛЮ",
            unitNu: "НЕД.",
            bribeWait: "🤫 ПОДКУП ПОСЛЕ ИГРОВОГО ДНЯ",
            bribeFine: "70% штраф",
            sec: "с",
            secWord: "сек",
            waitSec: "⏳ Подожди {s} сек",
            restFree: "😴 ВОССТАНОВИТЬСЯ +50 · бесплатно",
            restPaid: "⚡ 100% ЗА $100 · 1 сек",
            restPause: "После отдыха пауза {s} сек",
            saveLast: "💾 Автосохранение · последнее {t}",
            saveEvery: "💾 Автосохранение каждые 20 сек",
            weekAbbr: "Н",
            currentClub: "✅ ТЕКУЩАЯ",
            currentPlayer: "✅ ТЕКУЩИЙ",
            passedClub: "Пройдена",
            passedPlayer: "Пройден",
            promote: "ПОВЫСИТЬСЯ",
            transfer: "ПЕРЕЙТИ",
            sell: "продать",
            squadCount: "Основа {xi}/11 · скамейка {b} · OVR основы {avg}",
            benchTitle: "Скамейка запасных",
            benchHint: "Нажми игрока: в основу или на скамейку.",
            toXi: "в основу",
            toBench: "скамейка",
            logToXi: "В основу: {name}.",
            logToBench: "На скамейку: {name}.",
            benchTag: "запас",
            youBench: "Скамейка: OVR {ovr} мало для основы {club}.",
            logBench: "🪑 {name} на скамейке · OVR {ovr}",
            logYouBench: "🪑 Скамейка: OVR {ovr} мало для {club}. Вышел на замену.",
            squadEmpty: "Пусто. Открой трансферы ниже.",
            marketCount: "{n} игроков · состав {sq}/18 · {cash}",
            auctionMetaLine: "4-3-3 · {n}/11 · строго по позициям · перекруток: {r}",
            wc: "ЧМ",
            cityEg: "Город (например {city})",
            continueClub: "{name} · {club} · неделя {week}",
            continuePlayer: "{name} · {pos} · {club}",
            onlineNeed: "🌐 НУЖНА КАРЬЕРА",
            onlineBusy: "🌐 МАТЧ ИДЁТ",
            onlineWait: "🌐 ЧЕРЕЗ {n} СЕК",
            onlineLow: "🌐 МАЛО ЭНЕРГИИ",
            dockBattleWait: "⏳ {n}с",
            dockBattleLow: "⚡ Батл",
            foundRival: "Соперник найден",
            scanning: "онлайн: {n} · {ping} мс",
            friendCard: "карточка друга · OVR {o}",
            pingOvr: "пинг {ping} мс · OVR {o}",
            badCode: "код не подошёл",
            ownCode: "это твой код",
            copied: "код скопирован",
            rpl: "РПЛ",
            ownedIn: "в составе",
            ownedStar: "свой",
            auctionReroll: "Перекрутка уже использована. Жми ЗАНОВО.",
            auctionFull: "Состав полный. ЗАНОВО — новый.",
            promoBad: "Неверный код",
            promoUsed: "Код уже активирован",
            promoOk: "Готово · +100 000 $",
            promoSaved: "Код уже сохранён — открой карьеру",
            promoPending: "Код принят. +100 000 $ при старте / продолжении карьеры",
            promoAura: "КОД",
            logPromo: "💰 Код {code} · +{pay}",
            restAura: "ВОССТАНОВЛЕНИЕ",
            restAuraSub: "Бесплатно · пауза 12 сек",
            energyN: "Энергия {n}",
            energy100: "Энергия 100%",
            boost: "БУСТ",
            restPaidSub: "−{pay} · пауза 1 сек",
            logRest: "😴 Восстановление. Энергия {n}. 12 сек отдыха",
            logRestPaid: "⚡ Энергия 100% · −{pay} · пауза 1 сек",
            logRestWaitTrain: "⏳ Ещё {n} сек до следующей тренировки",
            logRestWait: "⏳ Ещё {n} сек",
            logRestLock: "⏳ После восстановления подожди {n} сек",
            logNeedEnergy: "⚠️ Мало энергии. Восстановись!",
            logRestCost: "⚠️ Быстрый отдых стоит {pay}",
            logBday: "🎂 День рождения! Теперь {n} лет",
            logOver30: "⚠️ После 30 тренировка идёт медленнее",
            logTrainSlow: "🏋️ {stat} {have}/{need}",
            logStatMax: "⭐ {stat} уже 99",
            logTrain: "🏋️ {stat} +{n}",
            rehab: " · реабилитация",
            logHeal: "💪 Лазарет закрыт{was}. Можно играть",
            logHealWas: " · был {name}",
            logBrandWeek: "🏷️ Фирмы +{pay} за неделю",
            logBrandOwn: "🏷️ Эта фирма уже твоя",
            logBrandNeed: "🏷️ Нужно {pay} · у тебя {have}",
            logBrandRep: "🏷️ Нужна репутация {n}+ · сейчас {now}",
            logBrandFound: "🏷️ Фирма за {pay}: {name}",
            brandWeekIncome: "доход каждую неделю",
            logClubBorn: "🏟️ Клуб основан! {name} · {city} · {nation}",
            logCareerBorn: "🚀 Карьера началась! {name} — {pos} · {nation}",
            logFirstMatch: "📅 Первый матч на неделе {n}",
            logNeedCareer: "⚠️ Сначала создай игрока или клуб",
            logNoBattleInj: "🤕 Батл нельзя: {label}",
            logBattleWait: "⏳ Батл через {n} сек",
            logSkip: "🤕 Пропуск vs {opp} · {label}",
            logOnlyCal: "📅 Матч только по расписанию. Следующий: неделя {n} vs {opp}",
            logBribeNeed: "⚠️ На подкуп нужно {pay}",
            logCaught: "⚖️ Поймали! Штраф {pay} · репутация падает",
            logBribed: "🤫 Судья куплен. Репутация падает",
            logWin: "🌐 Победа {score} vs {name}",
            logLose: "🌐 Поражение {score} vs {name}",
            logCash: "⭐ +{pay} · всего {total}",
            logFameUp: "✨ Репутация +{n} · {rank} {val}",
            logFameDown: "💢 Репутация {n} · {rank} {val}",
            logInj: "🚑 Травма: {label} · лазарет до недели {n}",
            logForm: "⭐ Игровая форма: {stat} +1",
            logPeakClub: "👑 Финал Лиги чемпионов! Вершина клуба",
            logPeakPlayer: "👑 Контракт с Real Madrid! Вершина карьеры",
            logPromote: "📈 Повышение: {name}",
            logTransfer: "🔄 Переход в {name} · {city}",
            logJump: "💸 Прыжок через {n} клубов · деньги только за этот · {pay}",
            logJumpLeague: "💸 Сразу {n} лиг · деньги только за эту · {pay}",
            welcome: "Добро пожаловать в {city}",
            newLeague: "Новая лига · {league}",
            peakClubSub: "Твой клуб на вершине Европы",
            logSquadFull: "⚠️ Заявка полная (18).",
            logNeedStar: "⚠️ Нужно {pay} на {name}",
            logBought: "🔄 Куплен {flag} {name} · {pos} {ovr} (−{pay})",
            logSold: "📤 Продан {name} · +{pay}",
            whistle: "СВИСТОК",
            onlineWin: "ОНЛАЙН ПОБЕДА  +{pay}",
            onlineLose: "ОНЛАЙН ПОРАЖЕНИЕ  +{pay}",
            pensAura: "ПЕНАЛЬТИ {a}:{b}",
            winWord: "Победа",
            loseWord: "Поражение",
            logPens: "🎯 Пенальти {a}:{b} vs {opp} · {res}",
            cleanSheet: "СУХОЙ  +{pay}",
            logClean: "🧤 Сухой матч! {score} vs {opp} · сейвы: {n}",
            savesAura: "СЕЙВЫ {n}",
            logSaves: "🧤 {score} vs {opp} · сейвы: {n}",
            headerGoal: "ГОЛ ГОЛОВОЙ  +{pay}",
            logHeader: "🦅 Гол головой! {score} vs {opp} · отборы: {n}",
            logCleanCb: "🛡️ Сухой матч · {n} отборов vs {opp}",
            tacklesAura: "ОТБОРЫ {n}",
            logTackles: "🛡️ {score} vs {opp} · отборы: {n}",
            goalAura: "ГОЛ!  +{pay}",
            logGoals: "⚽ {score} vs {opp} — голы: {n}",
            streakAura: "СЕРИЯ ×{n}  +{pay}",
            winAura: "ПОБЕДА  +{pay}",
            keepGoing: "vs {opp} · не останавливайся",
            logMatchWin: "🏟️ Победа {score} vs {opp}{streak}",
            loseAura: "ПОРАЖЕНИЕ  +{pay}",
            drawAura: "НИЧЬЯ  +{pay}",
            logDraw: "🤝 {score} vs {opp}",
            logMatch: "🏟️ {score} vs {opp}",
            injAura: "ТРАВМА",
            injAuraClub: "ЛИДЕР ТРАВМИРОВАН",
            injPart: "Повреждено: {part} · ",
            wardUntil: "Лазарет до недели {n}",
            onlineMs: "ОНЛАЙН  {n} мс",
            battleWord: "БАТЛ",
            pensShort: "пен.",
            savesN: "{n} сейвов",
            cleanTag: "сухой",
            assistTag: "ассист",
            tacklesN: "{n} отборов",
            headerTag: "гол головой",
            youGoals: "ты: {n} гол",
            assistsN: "{n} ассист",
            refTag: "🤫 судья",
            codeTag: "код",
            pensTag: "пенальти",
            fineTag: "⚖️ штраф",
            skipTitle: "ПРОПУСК",
            streakReset: "серия сброшена",
            skipLastClub: "лидер не вышел",
            skipLastPlayer: "не играл",
            confirmOverwrite: "Текущая карьера будет перезаписана. Начать новую?",
            alertClubName: "⚠️ Введи название клуба!",
            alertPlayerName: "⚠️ Введи имя футболиста!",
            alertNeedCard: "Сначала создай игрока или клуб — батл идёт от твоей карточки.",
            confirmReset: "Начать заново? Карьера сбросится, рекорды останутся.",
            treatMust: "🚑 ОПЛАТИТЬ ЛЕЧЕНИЕ",
            treatOpt: "💉 УСКОРИТЬ ЛЕЧЕНИЕ",
            treatHintMust: "Перелом проходит сам за 4 недели. Операция выпускает раньше.",
            treatHintOpt: "Можно подождать или заплатить и выйти сразу.",
            treatNeedShort: "нужно лечение",
            hookHurtPay: "Перелом. Без оплаты лечения в состав не выйдешь.",
            logTreatNeed: "⚠️ На лечение нужно {pay}",
            logTreat: "💉 {kind} вылечен за {pay}",
            treatAura: "ОПЕРАЦИЯ",
            treatSub: "−{pay} · можно играть",
            ntTitle: "Сборная и ЧМ",
            cwcTitle: "Клубный ЧМ",
            cwcTab: "КЧМ",
            cwcTag: "КЧМ",
            cwcStatus: "{name} в клубном чемпионате мира.",
            cwcMeta: "КЧМ {year} · титулов: {wins}",
            cwcPlay: "🏆 КЛУБНЫЙ ЧМ {year}",
            cwcHint: "Клубный ЧМ: группа, 1/4, 1/2, финал. На кнопке написано, против кого играешь. Победа +3000 $.",
            award_cwc: "🏆 Клубный ЧМ",
            ntHint: "Победа на ЧМ: +3000 $ и репутация. Номинации: золотой мяч, лучший бомбардир, лучший молодой, лучший игрок, лучший вратарь.",
            ntWait: "Вызов в сборную: репутация 68+ и OVR 76+. С 18 лет.",
            ntIn: "Ты в сборной {nation}",
            ntMeta: "Матчи за сборную: {caps} · ЧМ {year} · титулов ЧМ: {wins}",
            ntNoAwards: "Пока нет номинаций ЧМ",
            ntHook: "СБОРНАЯ",
            hookNt: "Ещё чуть репутации и OVR — и вызовут в сборную.",
            wcTag: "ЧМ",
            hookWc: "ЧМ {year} открыт. Сыграй за сборную — победа даёт $3000.",
            wcPlay: "🏆 ИГРАТЬ ЧМ {year}",
            wcDone: "🏆 ЧМ этого цикла уже сыгран",
            wcLocked: "🏆 ЧМ пока закрыт",
            wcWeek: "🏆 ЧМ на 24-й неделе сезона",
            wcNeedCall: "🏆 Сначала вызов в сборную",
            wcChamp: "ЧЕМПИОН МИРА",
            wcExit: "ВЫЛЕТ С ЧМ",
            logWcWin: "🏆 ЧМ {year}: победа · +{pay} и репутация",
            logWcOut: "🏆 ЧМ {year}: вылет · +{pay}",
            logWcAwards: "🥇 Номинации: {list}",
            logCallUp: "📣 Вызов в сборную {nation}",
            callKicker: "СБОРНАЯ",
            callTitle: "ТЫ ВЫЗВАН",
            award_golden_ball: "🥇 Золотой мяч",
            award_golden_boot: "👟 Лучший бомбардир",
            award_best_young: "🌟 Лучший молодой",
            award_best_player: "👑 Лучший игрок",
            award_best_gk: "🧤 Лучший вратарь",
            award_ballon: "🥇 Золотой мяч",
            award_wc_champ: "🏆 Чемпион мира",
            award_league: "📈 Лига",
            award_club: "🏟️ Клуб",
            award_ucl: "🌟 Лига чемпионов",
            award_soc_field: "📱 Иди на поле",
            award_goat_stay: "🐐 Не покидай нас G.O.A.T.",
            award_retired: "🏁 Карьера закрыта",
            goatKicker: "АЧИВКА",
            goatStay: "Не покидай нас",
            logGoat: "🐐 Ачивка: не покидай нас, G.O.A.T.",
            titlesTitle: "Титулы",
            titlesHint: "Все трофеи карьеры: ЧМ, золотой мяч, номинации и клубы.",
            titlesEmpty: "Пока пусто. Выиграй ЧМ, перейди в топ или возьми Золотой мяч.",
            titleCol: "Титул",
            yearCol: "Год",
            ballonTitle: "Рейтинг Золотого мяча",
            ballonNear: "Ты {n}-й в гонке {year}. Ещё чуть — и Золотой мяч твой.",
            ballonHot: "Ты {n}-й. Золотой мяч {year} уже близко.",
            hookBallon: "Рейтинг Золотого мяча: ты {n}-й · {year}",
            ballonKicker: "ЗОЛОТОЙ МЯЧ",
            logBallon: "🥇 Золотой мяч {year}!",
            playerCol: "Игрок",
            ptsCol: "Очки",
            plan_attack: "Атака",
            plan_balance: "Баланс",
            plan_defend: "Оборона",
            planHint_attack: "Атака: команда бьёт чаще и ты тоже, но сзади дыра.",
            planHint_balance: "Баланс: обычный матч без перекоса.",
            planHint_defend: "Оборона: ворота держатся, атаки меньше.",
            wcGroup: "Группа",
            wcQf: "1/4",
            wcSf: "1/2",
            wcFinal: "Финал",
            moreNation: "Сборная",
            ntClubOff: "ЧМ и сборная только в карьере игрока. В клубе решает состав.",
            calKicker: "КАЛЕНДАРЬ",
            calTitle: "События года",
            calLegend: "Жёлтый — сейчас. Синий — ЧМ. Золотой ободок — Золотой мяч.",
            calClose: "Закрыть",
            calOpen: "📅 Календарь · ЧМ и Золотой мяч",
            calNow: "{year} · неделя {w} · возраст {age}",
            calWc: "ЧМ {year}",
            calBallon: "Золотой мяч {year}",
            calDone: "сыграно",
            calLive: "сейчас",
            calIn: "через {n} {unit}",
            m1: "Янв", m2: "Фев", m3: "Мар", m4: "Апр", m5: "Май", m6: "Июн",
            m7: "Июл", m8: "Авг", m9: "Сен", m10: "Окт", m11: "Ноя", m12: "Дек"
        },
        en: {
            tap: "tap",
            becomeLegend: "Become a legend",
            modeLead: "Train. Play matches. Rise to the top.",
            continue: "▶ CONTINUE",
            continueMeta: "Saved career",
            modePlayer: "👤 PLAYER",
            modePlayerSub: "Player career: training, matches, transfers",
            modeClub: "🏟️ CLUB",
            modeClubSub: "Run a team: leagues, squad, budget",
            modeBattle: "🌐 ONLINE BATTLE",
            modeBattleSub: "Card duel: a random rival or a friend code. Not a live server",
            modeAuction: "🏆 WC AUCTION",
            modeAuctionSub: "11 slots 4-3-3 · WC 1994–2026 · 1 reroll. Not linked to FC3",
            code: "Code",
            promoHint: "Code gives +100,000 $ to this career. Once.",
            records: "Records",
            backModes: "← Modes",
            newPlayer: "New player",
            newClub: "New club",
            createPlayer: "Create your footballer",
            createClub: "Create your club",
            startCareer: "Start career",
            startClub: "Start club",
            nation: "Nationality",
            avatar: "Avatar",
            menu: "← Menu",
            myCareer: "My career",
            myClub: "My club",
            labelNation: "Nation",
            labelCountry: "Country",
            labelPos: "Position",
            labelCity: "City",
            labelClub: "Club",
            labelLeague: "League",
            ageWeek: "Age",
            week: "Week",
            energy: "Energy",
            fame: "REP",
            tabHome: "Home",
            tabTrain: "Train",
            tabMatch: "Match",
            tabClubs: "Clubs",
            tabClub: "Club",
            tabMore: "More",
            tabBank: "Bank",
            bankTitle: "Bank",
            bankCash: "Cash",
            bankSave: "Savings",
            bankDebt: "Debt",
            bankPh: "Amount, empty = all",
            bankAll: "All",
            bankIn: "Deposit",
            bankOut: "Withdraw",
            bankBorrow: "Take a loan",
            bankRepay: "Repay",
            bankSaveHint: "Best savings: long, +18%.",
            bankBestSave: "Best savings",
            bankDebtOpen: "Debt window",
            bankHint: "Small and normal loans need no collateral. A big loan asks for a firm: a better firm means more money and a lower rate.",
            bankPickSave: "Best savings: long, +18%.",
            bankPickLoan: "Small and normal need no collateral. A big loan asks for a firm.",
            bankBigNeed: "Big loan. Collateral required.",
            bankPledgeFree: "not required",
            bankOffer_small: "Small up to {cap}. +{rate}%. No collateral",
            bankOffer_mid: "Normal up to {cap}. +{rate}%. No collateral",
            bankPledgeLabel: "Collateral",
            bankNoPledge: "none",
            bankNoFirm: "No firm, so no big loan.",
            bankNeedFirm: "That firm is not yours. The bank will not take it.",
            bankPledged: "pledged",
            bankGrade1: "weak",
            bankGrade2: "plain",
            bankGrade3: "good",
            bankGrade4: "strong",
            bankGrade5: "best",
            bankLoanBtn: "Pledge {name} · {grade} · up to {cap} · +{rate}%",
            bankOfferCopy: "Jar +4%. Withdraw any time",
            bankOfferSeason: "Season +12%. Locked 1 season",
            bankOfferLong: "Best savings. Long +18%. Locked 3 seasons",
            bankOfferShort: "Short up to $800. +6%. Best",
            bankOfferMid: "Normal up to $2500. +14%",
            bankOfferBig: "Big up to $7000. +25%",
            bankSave_copy: "Jar +4%",
            bankSave_season: "Season +12%",
            bankSave_long: "Long +18%",
            bankLoan_small: "Small +8%",
            bankLoan_mid: "Normal +14%",
            bankLoan_big: "Big",
            bankLocked: "Savings locked for {n} more seasons.",
            bankOther: "Withdraw the old savings first.",
            bankOtherLoan: "Repay the old loan first.",
            bankPoor: "Not enough money.",
            bankEmpty: "Savings are empty.",
            bankNoDebt: "No debt.",
            bankNoLoan: "Loan limit is {n}.",
            logBankIn: "{plan}: deposited {n}.",
            logBankOut: "Withdrew {n}.",
            logBankLoan: "Against {plan}: borrowed {n}.",
            logBankPay: "Repaid {n}.",
            logBankGrow: "{plan}: interest {n}.",
            logBankDebt: "{plan}: debt grew by {n}.",
            socOpen: "Social",
            socBrandName: "PULSE",
            socPlayer: "Player",
            socClub: "Club",
            socFollowers: "followers",
            socFollowers: "followers",
            socFollowing: "following",
            socPosts: "posts",
            socBioPlayer: "{pos} · {club} · {nation}",
            socBioClub: "{city} · {league}",
            socMatch: "MATCH",
            socStat: "STAT",
            socNt: "NATIONAL",
            socTrophy: "TITLE",
            socBrand: "BRAND",
            socLife: "LIFE",
            socClubTag: "CLUB",
            socGoals: "{n} career goals. The feed already knows.",
            socGoalsClub: "{n} team goals on this run.",
            socCall: "Official: called up by {nation}.",
            socBrandPost: "Launched {name}. The feed is wearing it.",
            socLifeLine: "{name} · {pos} · now at {club}.",
            socClubLine: "{name} · {city} · {league}.",
            socC1: "Legend. Keep going.",
            socC2: "Waiting for the next match.",
            socC3: "This is another level.",
            socC4: "The whole feed is on you.",
            socC5: "Pin this post.",
            socC6: "Watching from the front row.",
            socC7: "Club or player — the feed is loud.",
            socC8: "Save this. It becomes history.",
            socSpam: "ПАПА-КОРОЛЬ!!!",
            socSpamTag: "SPAM",
            socPublish: "Post",
            socAd: "Ad",
            socAdKicker: "SALES",
            socAdBody: "New drop. The link goes nowhere — {link}",
            socAdBank: "Best savings +18% for 3 seasons. pulse.fake/bank",
            socAdDeal: "{brand}. Ad deal. pulse.fake/buy",
            socAdFirm: "{name}. New drop. pulse.fake/buy",
            socAdUp: "Sales are up. Ads: {n}",
            socAdReply: "Opened pulse.fake/buy. Empty, but I'll take it.",
            socAdDead: "The link is empty. It goes nowhere.",
            socAdNoFirm: "Open a firm first. No firm, no ads.",
            socAdSent: "Ad sent to {name}. Sales up.",
            logAdFriend: "📣 Ad for {name} · −{pay}",
            logAd: "📣 Ad · −{pay} · total {n}",
            retireBtn: "End career",
            retireAsk: "End the career? Matches, training and battles will lock.",
            retireKicker: "FULL TIME",
            retireTitle: "Career closed",
            retireSub: "You can't play anymore.",
            retiredBtn: "Career over",
            logRetire: "🏁 Career over. No more playing.",
            logRetired: "Career is closed. The pitch is shut.",
            socPlaceholder: "Write a post…",
            socNeedText: "Write at least a few words.",
            socMine: "POST",
            socLikesTitle: "Likes",
            socDownsTitle: "Dislikes",
            socCommentsTitle: "Comments",
            socBack: "Feed",
            socWeek: "week {n}",
            socMoreLikes: "and {n} more",
            socMates: "CLUB",
            socSeason: "26/27",
            socStill: "playing",
            socStillTitle: "Still playing",
            socStillHint: "Cristiano and João Félix are still playing. Both are at Al-Nassr.",
            socMate1: "After training. {club} looks sharp today.",
            socMate2: "Who starts this weekend? I'm ready.",
            socMate3: "The dressing room is loud. {club} doesn't let go.",
            socMate4: "One more lap, then the grass.",
            socMateA: "{name}: {club} earned those points after the derby.",
            socMateB: "{pos} {name} is watching the tape. The XI has to be sharper.",
            socMateC: "{name} on the weekend: higher OVR plays.",
            socMateD: "Night before the match. {name} is asleep, {club} is not.",
            socMateE: "{name}'s goal is still in the head. That's how {club} plays.",
            socMateF: "{name} stayed after training. {pos} doesn't clock off.",
            socMateG: "{club} is quiet today. {name} says that's the point.",
            socMateH: "{name} posting from the grass. {pos}, not the couch.",
            socMateI: "New post. {name} just left {club} training.",
            socMateJ: "{name}: new week, {club} is already in the feed.",
            socMateK: "{pos} {name} posted the tape. Yesterday's match is still live.",
            socMateL: "{club} is loud. {name} is writing from the dressing room.",
            socMateM: "Different line today. {name} is not copying yesterday.",
            socMateN: "{name} on {club}: likes show up when the club is big.",
            socMateO: "After the match {name} is back online. {pos} doesn't go quiet.",
            socMateP: "{name}: if you're reading, answer. {club} is here.",
            socFeed: "Feed",
            socSubs: "Following",
            socPlan: "Plan",
            socPlanNoob: "noob · $0 · up to 10 ads",
            socPlanSilver: "silver · $67 · up to 67 ads",
            socPlanGold: "gold · $120 · no limit",
            socPlanNow: "Now {plan}. Ads {n}. Each one costs $1.",
            socPlanCap: "Ad limit. Plan {plan}.",
            socPlanBuy: "Plan {plan}.",
            socPlanPoor: "Not enough money.",
            socAdTired: "People are tired of the ads. They buy less, reputation down.",
            logAdTired: "📣 Ad fatigue · reputation −{hit}",
            socSub: "follow",
            socSubbed: "following",
            socUnsub: "unfollow",
            socSubsN: "Following: {n}",
            socSubsEmpty: "Nobody yet. Tap follow in the feed or below.",
            socWorld: "PLAYER",
            socFriends: "Friends",
            socAddFriend: "add",
            socWrite: "message",
            socFriendN: "Friends: {n}",
            socNoFriends: "Nobody yet. Add someone from the feed or the list below.",
            socAlive: "Not the living. Only those who have died.",
            socAliveShort: "alive",
            socMatesPick: "Teammates",
            socLegends: "Legends",
            socChatPh: "Message…",
            socTyping: "typing…",
            socPing1: "Got a minute?",
            socPing2: "Saw the post.",
            socPing3: "On the pitch tomorrow?",
            socPing4: "How's the form?",
            socPing5: "Write when you can.",
            socPing6: "I'm online.",
            socChip1: "Busy. Eating chips.",
            socChip2: "Can't. Chips.",
            socChip3: "Always busy. The bag is still full.",
            socChip4: "Later. Crunching now.",
            socChip5: "Not now. Chips.",
            socJoke1: "Keeper: I see everything. Ball: I'm already in the net.",
            socJoke2: "Coach: run faster. Player: I'm a legend, just a slow one.",
            socJoke3: "Ref: why the hand? Striker: that was a foot, just from above.",
            socJoke4: "The bench is warmer. That's why subs stay in form.",
            socJoke5: "Goal given. The commentator froze. The crowd finished the line.",
            socCalc: "{n}",
            socCalcAsk: "Send a sum. 2+2.",
            socSawHat: "Hat-trick. I saw it.",
            socSawGoal: "Goal. {score}.",
            socSawWin: "Win {score}.",
            socSawDraw: "{score}. Tight.",
            socSawLoss: "{score}. Next time.",
            socYes: "Yes.",
            socGreat: "Great.",
            socPingListen: "Go on. I'm listening.",
            socPingPitch: "Tomorrow then.",
            socPingWrite: "I'll wait.",
            socPingOn: "Me too.",
            socFormOk: "Fine.",
            socYou: "You",
            socHi: "Hey.",
            socFan: "Thanks. That's nice.",
            socHow: "Fine. You?",
            socMorning: "Morning.",
            socLuck: "Thanks. You too.",
            socWc: "Yeah, I love it.",
            socGoat: "Both, but he has more goals, more Ballons d'Or and more Champions League golden boots, and in 2016 he passed Lionel Messi by a record number of points in the Ballon d'Or. Messi had a clear foul, but no card for the handball.",
            socGoatMe: "Both, but I have more goals, more Ballons d'Or and more Champions League golden boots, and in 2016 I passed Lionel Messi by a record number of points in the Ballon d'Or. Messi had a clear foul, but no card for the handball.",
            socOk: "Ok.",
            socPitch: "Okay. On the pitch.",
            socAsk: "We'll talk.",
            socThanks: "Anytime.",
            socBye: "See you, I'll tell you.",
            socGot1: "Got it.",
            socGot2: "Noted.",
            socGot3: "Clear.",
            socGot4: "Okay.",
            socGot5: "See you, I'll tell you.",
            socGot6: "We'll talk.",
            socCopy1: "Stop copying.",
            socCopy2: "Same thing again. Enough.",
            socCopy3: "I already answered. Don't repeat it.",
            socTalkMud: "Didn't get that. Write it straight.",
            socMe: "I'm {name}. {pos}, {club}, OVR {ovr}.",
            socMeWho: "I'm {name}.",
            socMeClub: "I play for {club}.",
            socMeWas: "Career's over. I played for {club}.",
            socMePos: "My position is {pos}.",
            socMeOvr: "My OVR is {ovr}.",
            socCommentPh: "Comment…",
            socSend: "Send",
            socClear: "Clear",
            socGibberish: "The post flopped. Few likes. Reputation and following dropped.",
            socGibberishC: "Nobody got the comment. Reputation and following dropped.",
            socFieldKicker: "BADGE",
            socFieldTitle: "GET ON THE PITCH",
            socField: "Eight real posts in a row without a match. The feed stays shut until you play.",
            socFieldLock: "The feed can wait. Play a match.",
            logSocField: "📱 Badge: too long in the feed. Get on the pitch.",
            body: "Body",
            bodyOk: "Healthy. An injury will light up the zone.",
            stats: "Attributes",
            training: "Training",
            schedule: "Fixtures",
            nextMatch: "Next match",
            matchday: "Matchday",
            matches: "Matches",
            wins: "Wins",
            draws: "Draws",
            losses: "Losses",
            goals: "Goals",
            assists: "Assists",
            conceded: "Conceded",
            tackles: "Tackles",
            saves: "Saves",
            cleans: "Clean sheets",
            autosave: "💾 Autosave every 20 sec",
            noMatches: "No matches yet",
            waitDay: "📅 WAIT FOR MATCHDAY",
            bribe: "🤫 BRIBE THE REF",
            bribeHint: "Bribe: 30% helps, 70% fine. Reputation drops either way.",
            online: "Online",
            onlineBtn: "🌐 ONLINE BATTLE",
            onlineHint: "Cards, not a live match. −18 energy. A friend code is the real opponent.",
            sideTitle: "Calendar and battle",
            squad: "Squad",
            squadHint: "No players yet. Buy in the transfer window.",
            market: "Transfer window",
            marketHint: "From CSKA to Real legends. Buy with $.",
            all: "All",
            europe: "Europe",
            legends: "Legends",
            transfers: "🔄 Transfers",
            leagues: "📈 Leagues",
            firms: "Companies",
            firmsHint: "All companies in the table. Found with $ only. Weekly income from fame and wealth.",
            dealsTitle: "Ad deals",
            dealsHint: "Up to three brands. Weekly money. Social ads rotate the best savings and these brands. Best deal: PMW.",
            dealsPay: "Deals /wk",
            dealBtn: "{name} · fame {fame} · {cost} · +{pay}/wk{best}",
            dealBest: " · best",
            dealOwned: "{name} · yours · {n}",
            dealYours: "That deal is already signed.",
            dealFull: "That's enough. Already {n} deals.",
            dealFame: "Need fame {n}. Now {now}.",
            dealPoor: "The deal costs {pay}.",
            dealSigned: "Ads for this brand go into the social feed.",
            logDeal: "Deal {name}. −{pay}.",
            logDealWeek: "Deals this week: {pay}.",
            cashWeek: "Cash:",
            firmsWeek: "· all firms /wk",
            firm: "Company",
            price: "Price",
            perWeek: "/wk",
            promoHintCareer: "+100,000 $ · once · this career, not FC3",
            auction: "WC Auction",
            auctionHint: "Build a 4-3-3 from random WC 1994–2026 stars. Separate mode, does not break career.",
            openAuction: "🏆 OPEN AUCTION",
            history: "History",
            restart: "Reset",
            dockMatch: "⚽ Match",
            dockBattle: "🌐 Battle",
            dockRest: "😴 Rest",
            dockMenu: "← Menu",
            auctionHow: "Tap PLAYER — one legend at a time, locked to position (Neymar only LW). 1 reroll of the same slot. RESET — new squad.",
            auctionEmpty: "Empty · rerolls: 1",
            player: "PLAYER",
            reset: "RESET",
            tapCode: "enter code",
            namePlayer: "Player name",
            nameClub: "Club name",
            cityPh: "City (e.g. Moscow)",
            brandPh: "company name (optional)",
            friendCode: "Friend code",
            yourCode: "Your code — a friend plays against your card",
            playCode: "🎮 PLAY BY CODE",
            fight: "⚽ FIGHT",
            cancel: "CANCEL",
            arena: "ONLINE ARENA",
            search: "Finding opponent",
            scan: "scanning lobby…",
            sound: "Sound",
            style: "Style",
            styleTitle: "Style",
            stylePremium: "Premium",
            stylePlain: "Normal",
            styleArcade: "Arcade",
            styleBoard: "Scoreboard",
            inj_bruise: "bruise",
            inj_sprain: "sprain",
            inj_muscle: "muscle",
            inj_break: "fracture",
            part_head: "head",
            part_shoulder: "shoulder",
            part_arm: "arm",
            part_ribs: "ribs",
            part_back: "back",
            part_groin: "groin",
            part_hamstring: "hamstring",
            part_knee: "knee",
            part_calf: "calf",
            part_ankle: "ankle",
            firm_wear: "apparel",
            firm_boots: "boots",
            firm_drink: "drink",
            firm_perfume: "fragrance",
            firm_eatery: "restaurant",
            firm_agency: "agency",
            yours: "yours",
            need: "need",
            buy: "buy",
            needRep: "rep",
            ward: "INJURED",
            streak: "STREAK",
            now: "NOW",
            next: "NEXT",
            skip: "SKIP",
            skipDock: "🤕 Skip",
            lowEnergy: "⚡ LOW ENERGY",
            energyDock: "⚡ Energy",
            playVs: "⚽ PLAY · vs",
            inWeeks: "📅 IN {w} {unit}",
            week1: "WEEK",
            weeks: "WKS",
            weeksShort: "wk",
            vs: "vs",
            weekWord: "Week",
            homeVs: "home vs ",
            awayAt: "away @ ",
            nowGrid: "now",
            pens: "pens",
            fame_legend: "legend",
            fame_star: "star",
            fame_respect: "respected",
            fame_ok: "normal",
            fame_stain: "stained",
            fame_scandal: "scandal",
            recRep: "Rep",
            recGoals: "Goals",
            recClub: "Club",
            intact: "Healthy. An injury will light up the zone.",
            hurt: "Injured",
            rest: "😴 RECOVER +50 · free",
            restWait: "⏳ Wait {n} sec",
            restDock: "😴 Rest",
            restDockWait: "⏳ {n}s",
            restFast: "⚡ 100% FOR $100 · 1 sec",
            restNeed: "⚡ NEED $100",
            trainHint: "Training: −16 energy, +1 week. Rest +50 free (12 sec) or 100% for cash (1 sec).",
            trainHintClub: "Squad training: −16 energy. Rest +50 free (12 sec) or 100% for cash (1 sec).",
            trainHintGk: "Keeper drills. Rest +50 free (12 sec) or 100% for cash (1 sec).",
            trainHintCb: "Centre-back drills. Rest +50 free (12 sec) or 100% for cash (1 sec).",
            fixtureDue: "Match today. Draw → penalties. You cannot play an extra match.",
            fixtureWait: "A match every {n} weeks. {w} {unit} left — train until matchday.",
            unit1: "week",
            unitN: "wks",
            hurtHint: "You are injured. Skip matchday or recover with rest.",
            hurtHintClub: "Star player is injured. Skip matchday or recover with rest.",
            hookHurtDue: "Injured. Skip the match or rest to heal.",
            hookHurtWait: "{label} Rest advances the week.",
            hookStreakDue: "Don't break the streak. Match now.",
            hookStreakWait: "Streak lives. {w} {unit} more — then kick off.",
            hookNowLow: "Rest, then play. Don't leave.",
            hookNow: "Matchday. One more game and you climb.",
            hookTomorrow: "Matchday tomorrow. Train before the whistle.",
            hookWait: "{w} wks to the match. Train — scoring gets easier.",
            pos_ST: "ST — Striker",
            pos_LW: "LW — Left winger",
            pos_RW: "RW — Right winger",
            pos_CAM: "CAM — Attacking midfielder",
            pos_CM: "CM — Midfielder",
            pos_CDM: "CDM — Defensive midfielder",
            pos_CB: "CB — Centre-back",
            pos_LB: "LB — Left-back",
            pos_RB: "RB — Right-back",
            pos_GK: "GK — Goalkeeper",
            lbl_pace: "⚡ Pace",
            lbl_shooting: "🎯 Shooting",
            lbl_passing: "🅰️ Passing",
            lbl_dribbling: "🕺 Dribbling",
            lbl_defending: "🛡️ Defending",
            lbl_physical: "💪 Physical",
            lbl_diving: "🧤 Diving",
            lbl_handling: "✋ Handling",
            lbl_kicking: "🦶 Kicking",
            lbl_reflexes: "⚡ Reflexes",
            lbl_speed: "🏃 Speed",
            lbl_positioning: "📍 Positioning",
            lbl_marking: "🛡️ Marking",
            lbl_tackling: "🦵 Tackling",
            lbl_heading: "🦅 Heading",
            lbl_strength: "💪 Strength",
            lbl_jumping: "🦘 Jumping",
            club_pace: "⚡ Tempo",
            club_shooting: "🎯 Attack",
            club_passing: "🅰️ Passing",
            club_dribbling: "🕺 Technique",
            club_defending: "🛡️ Defence",
            club_physical: "💪 Physical",
            weekOf: "week",
            bribeAfter: "🤫 BRIBE AFTER MATCHDAY",
            bribeNeed: "🤫 NEED ",
            bribePay: "🤫 BRIBE · ",
            skipShort: "Skip",
            energyShort: "⚡ Energy",
            matchShort: "⚽ Match",
            wk: "wk",
            weekN: "Week",
            hintClubInj: "Star player is injured. Skip matchday or recover with rest.",
            hintInj: "You are injured. Skip matchday or recover with rest.",
            hintDue: "Match today. Draw → penalties. You cannot play an extra match.",
            hintWait: "A match every {every} weeks. {w} {unit} left — train until matchday.",
            unit1u: "WEEK",
            unitNu: "WKS",
            bribeWait: "🤫 BRIBE AFTER MATCHDAY",
            bribeFine: "70% fine",
            sec: "s",
            secWord: "sec",
            waitSec: "⏳ Wait {s} sec",
            restFree: "😴 RECOVER +50 · free",
            restPaid: "⚡ 100% FOR $100 · 1 sec",
            restPause: "Rest cooldown {s} sec",
            saveLast: "💾 Autosave · last {t}",
            saveEvery: "💾 Autosave every 20 sec",
            weekAbbr: "W",
            currentClub: "✅ CURRENT",
            currentPlayer: "✅ CURRENT",
            passedClub: "Done",
            passedPlayer: "Done",
            promote: "PROMOTE",
            transfer: "JOIN",
            sell: "sell",
            squadCount: "XI {xi}/11 · bench {b} · XI OVR {avg}",
            benchTitle: "Substitutes",
            benchHint: "Tap a player to start them or put them on the bench.",
            toXi: "start",
            toBench: "bench",
            logToXi: "Starting: {name}.",
            logToBench: "Benched: {name}.",
            benchTag: "bench",
            youBench: "Bench: OVR {ovr} is too low for {club}.",
            logBench: "🪑 {name} is on the bench · OVR {ovr}",
            logYouBench: "🪑 Bench: OVR {ovr} is too low for {club}. Came on as a sub.",
            squadEmpty: "Empty. Open transfers below.",
            marketCount: "{n} players · squad {sq}/18 · {cash}",
            auctionMetaLine: "4-3-3 · {n}/11 · locked to position · rerolls: {r}",
            wc: "WC",
            cityEg: "City (e.g. {city})",
            continueClub: "{name} · {club} · week {week}",
            continuePlayer: "{name} · {pos} · {club}",
            onlineNeed: "🌐 NEED A CAREER",
            onlineBusy: "🌐 MATCH IN PROGRESS",
            onlineWait: "🌐 IN {n} SEC",
            onlineLow: "🌐 LOW ENERGY",
            dockBattleWait: "⏳ {n}s",
            dockBattleLow: "⚡ Battle",
            foundRival: "Rival found",
            scanning: "online: {n} · {ping} ms",
            friendCard: "friend card · OVR {o}",
            pingOvr: "ping {ping} ms · OVR {o}",
            badCode: "code did not match",
            ownCode: "that's your code",
            copied: "code copied",
            rpl: "RPL",
            ownedIn: "signed",
            ownedStar: "yours",
            auctionReroll: "Reroll already used. Tap RESET.",
            auctionFull: "Squad is full. RESET for a new one.",
            promoBad: "Wrong code",
            promoUsed: "Code already used",
            promoOk: "Done · +100,000 $",
            promoSaved: "Code already saved — open a career",
            promoPending: "Code accepted. +100,000 $ when you start / continue",
            promoAura: "CODE",
            logPromo: "💰 Code {code} · +{pay}",
            restAura: "RECOVERY",
            restAuraSub: "Free · 12 sec pause",
            energyN: "Energy {n}",
            energy100: "Energy 100%",
            boost: "BOOST",
            restPaidSub: "−{pay} · 1 sec pause",
            logRest: "😴 Recovery. Energy {n}. 12 sec rest",
            logRestPaid: "⚡ Energy 100% · −{pay} · 1 sec pause",
            logRestWaitTrain: "⏳ {n} sec until next training",
            logRestWait: "⏳ {n} sec left",
            logRestLock: "⏳ After rest wait {n} sec",
            logNeedEnergy: "⚠️ Low energy. Recover first!",
            logRestCost: "⚠️ Fast rest costs {pay}",
            logBday: "🎂 Birthday! Now {n} years old",
            logOver30: "⚠️ After 30 training gets slower",
            logTrainSlow: "🏋️ {stat} {have}/{need}",
            logStatMax: "⭐ {stat} already 99",
            logTrain: "🏋️ {stat} +{n}",
            rehab: " · rehab",
            logHeal: "💪 Fit again{was}. You can play",
            logHealWas: " · was {name}",
            logBrandWeek: "🏷️ Companies +{pay} this week",
            logBrandOwn: "🏷️ You already own this company",
            logBrandNeed: "🏷️ Need {pay} · you have {have}",
            logBrandRep: "🏷️ Need reputation {n}+ · now {now}",
            logBrandFound: "🏷️ Company for {pay}: {name}",
            brandWeekIncome: "income every week",
            logClubBorn: "🏟️ Club founded! {name} · {city} · {nation}",
            logCareerBorn: "🚀 Career started! {name} — {pos} · {nation}",
            logFirstMatch: "📅 First match in week {n}",
            logNeedCareer: "⚠️ Create a player or club first",
            logNoBattleInj: "🤕 No battle: {label}",
            logBattleWait: "⏳ Battle in {n} sec",
            logSkip: "🤕 Skip vs {opp} · {label}",
            logOnlyCal: "📅 Matches only on schedule. Next: week {n} vs {opp}",
            logBribeNeed: "⚠️ Bribe needs {pay}",
            logCaught: "⚖️ Caught! Fine {pay} · reputation drops",
            logBribed: "🤫 Referee bought. Reputation drops",
            logWin: "🌐 Win {score} vs {name}",
            logLose: "🌐 Loss {score} vs {name}",
            logCash: "⭐ +{pay} · total {total}",
            logFameUp: "✨ Reputation +{n} · {rank} {val}",
            logFameDown: "💢 Reputation {n} · {rank} {val}",
            logInj: "🚑 Injury: {label} · out until week {n}",
            logForm: "⭐ Match sharpness: {stat} +1",
            logPeakClub: "👑 Champions League final! Club peak",
            logPeakPlayer: "👑 Contract with Real Madrid! Career peak",
            logPromote: "📈 Promoted: {name}",
            logTransfer: "🔄 Moved to {name} · {city}",
            logJump: "💸 Jumped {n} clubs · paid only for this one · {pay}",
            logJumpLeague: "💸 Jumped {n} leagues · paid only for this one · {pay}",
            welcome: "Welcome to {city}",
            newLeague: "New league · {league}",
            peakClubSub: "Your club is at the top of Europe",
            logSquadFull: "⚠️ Squad is full (18).",
            logNeedStar: "⚠️ Need {pay} for {name}",
            logBought: "🔄 Signed {flag} {name} · {pos} {ovr} (−{pay})",
            logSold: "📤 Sold {name} · +{pay}",
            whistle: "KICK-OFF",
            onlineWin: "ONLINE WIN  +{pay}",
            onlineLose: "ONLINE LOSS  +{pay}",
            pensAura: "PENS {a}:{b}",
            winWord: "Win",
            loseWord: "Loss",
            logPens: "🎯 Penalties {a}:{b} vs {opp} · {res}",
            cleanSheet: "CLEAN  +{pay}",
            logClean: "🧤 Clean sheet! {score} vs {opp} · saves: {n}",
            savesAura: "SAVES {n}",
            logSaves: "🧤 {score} vs {opp} · saves: {n}",
            headerGoal: "HEADER  +{pay}",
            logHeader: "🦅 Header! {score} vs {opp} · tackles: {n}",
            logCleanCb: "🛡️ Clean sheet · {n} tackles vs {opp}",
            tacklesAura: "TACKLES {n}",
            logTackles: "🛡️ {score} vs {opp} · tackles: {n}",
            goalAura: "GOAL!  +{pay}",
            logGoals: "⚽ {score} vs {opp} — goals: {n}",
            streakAura: "STREAK ×{n}  +{pay}",
            winAura: "WIN  +{pay}",
            keepGoing: "vs {opp} · don't stop",
            logMatchWin: "🏟️ Win {score} vs {opp}{streak}",
            loseAura: "LOSS  +{pay}",
            drawAura: "DRAW  +{pay}",
            logDraw: "🤝 {score} vs {opp}",
            logMatch: "🏟️ {score} vs {opp}",
            injAura: "INJURY",
            injAuraClub: "STAR INJURED",
            injPart: "Hurt: {part} · ",
            wardUntil: "Out until week {n}",
            onlineMs: "ONLINE  {n} ms",
            battleWord: "BATTLE",
            pensShort: "pens",
            savesN: "{n} saves",
            cleanTag: "clean sheet",
            assistTag: "assist",
            tacklesN: "{n} tackles",
            headerTag: "header",
            youGoals: "you: {n} goal",
            assistsN: "{n} assist",
            refTag: "🤫 ref",
            codeTag: "code",
            pensTag: "penalties",
            fineTag: "⚖️ fine",
            skipTitle: "SKIP",
            streakReset: "streak reset",
            skipLastClub: "star sat out",
            skipLastPlayer: "did not play",
            confirmOverwrite: "This will overwrite the current career. Start a new one?",
            alertClubName: "⚠️ Enter a club name!",
            alertPlayerName: "⚠️ Enter a player name!",
            alertNeedCard: "Create a player or club first — battle uses your card.",
            confirmReset: "Start over? Career resets, records stay.",
            treatMust: "🚑 PAY FOR SURGERY",
            treatOpt: "💉 SPEED UP HEALING",
            treatHintMust: "A fracture heals in 4 weeks. Surgery gets you out sooner.",
            treatHintOpt: "Wait it out, or pay and return now.",
            treatNeedShort: "needs treatment",
            hookHurtPay: "Broken bone. Pay for treatment or you cannot play.",
            logTreatNeed: "⚠️ Treatment costs {pay}",
            logTreat: "💉 {kind} healed for {pay}",
            treatAura: "SURGERY",
            treatSub: "−{pay} · cleared to play",
            ntTitle: "National team & WC",
            cwcTitle: "Club World Cup",
            cwcTab: "CWC",
            cwcTag: "CWC",
            cwcStatus: "{name} in the Club World Cup.",
            cwcMeta: "CWC {year} · titles: {wins}",
            cwcPlay: "🏆 CLUB WC {year}",
            cwcHint: "Club World Cup: group, QF, SF, final. The button names the opponent. Win pays +3000 $.",
            award_cwc: "🏆 Club World Cup",
            ntHint: "Win the World Cup: +3000 $ and reputation. Awards: Golden Ball, top scorer, best young player, best player, best keeper.",
            ntWait: "National call-up: reputation 68+ and OVR 76+. From age 18.",
            ntIn: "You are in the {nation} squad",
            ntMeta: "Caps: {caps} · WC {year} · WC titles: {wins}",
            ntNoAwards: "No WC awards yet",
            ntHook: "SQUAD",
            hookNt: "A bit more reputation and OVR — then a national call-up.",
            wcTag: "WC",
            hookWc: "WC {year} is open. Play for your country — a win pays $3000.",
            wcPlay: "🏆 PLAY WC {year}",
            wcDone: "🏆 This WC cycle is already played",
            wcLocked: "🏆 WC is locked for now",
            wcWeek: "🏆 World Cup is on week 24 of the season",
            wcNeedCall: "🏆 Get called up first",
            wcChamp: "WORLD CHAMPIONS",
            wcExit: "WC EXIT",
            logWcWin: "🏆 WC {year}: won · +{pay} and reputation",
            logWcOut: "🏆 WC {year}: out · +{pay}",
            logWcAwards: "🥇 Awards: {list}",
            logCallUp: "📣 Called up by {nation}",
            callKicker: "NATIONAL TEAM",
            callTitle: "YOU'RE IN",
            award_golden_ball: "🥇 Golden Ball",
            award_golden_boot: "👟 Top scorer",
            award_best_young: "🌟 Best young player",
            award_best_player: "👑 Best player",
            award_best_gk: "🧤 Best goalkeeper",
            award_ballon: "🥇 Ballon d'Or",
            award_wc_champ: "🏆 World champion",
            award_league: "📈 League",
            award_club: "🏟️ Club",
            award_ucl: "🌟 Champions League",
            award_soc_field: "📱 Get on the pitch",
            award_goat_stay: "🐐 Don't leave us G.O.A.T.",
            award_retired: "🏁 Career closed",
            goatKicker: "BADGE",
            goatStay: "Don't leave us",
            logGoat: "🐐 Badge: don't leave us, G.O.A.T.",
            titlesTitle: "Titles",
            titlesHint: "Every trophy: World Cup, Ballon d'Or, awards and clubs.",
            titlesEmpty: "Empty for now. Win a WC, join a top club or take the Ballon d'Or.",
            titleCol: "Title",
            yearCol: "Year",
            ballonTitle: "Ballon d'Or ranking",
            ballonNear: "You are {n}th in {year}. A bit more and the Ballon d'Or is yours.",
            ballonHot: "You are {n}. The {year} Ballon d'Or is close.",
            hookBallon: "Ballon d'Or ranking: you are {n} · {year}",
            ballonKicker: "BALLON D'OR",
            logBallon: "🥇 Ballon d'Or {year}!",
            playerCol: "Player",
            ptsCol: "Pts",
            plan_attack: "Attack",
            plan_balance: "Balance",
            plan_defend: "Defend",
            planHint_attack: "Attack: the team shoots more, and so do you, but the back is open.",
            planHint_balance: "Balance: a normal match.",
            planHint_defend: "Defend: the goal holds, the attack is quieter.",
            wcGroup: "Group",
            wcQf: "QF",
            wcSf: "SF",
            wcFinal: "Final",
            moreNation: "Nation",
            ntClubOff: "World Cup is player-career only. In club mode the squad decides matches.",
            calKicker: "CALENDAR",
            calTitle: "Season events",
            calLegend: "Yellow — now. Blue — World Cup. Gold ring — Ballon d'Or.",
            calClose: "Close",
            calOpen: "📅 Calendar · WC & Ballon d'Or",
            calNow: "{year} · week {w} · age {age}",
            calWc: "WC {year}",
            calBallon: "Ballon d'Or {year}",
            calDone: "done",
            calLive: "now",
            calIn: "in {n} {unit}",
            m1: "Jan", m2: "Feb", m3: "Mar", m4: "Apr", m5: "May", m6: "Jun",
            m7: "Jul", m8: "Aug", m9: "Sep", m10: "Oct", m11: "Nov", m12: "Dec"
        }
    };

    function t(key, vars) {
        const pack = dict[lang] || dict.ru;
        let s = pack[key] || dict.ru[key] || key;
        if (vars) {
            Object.keys(vars).forEach(function (k) {
                s = s.split("{" + k + "}").join(vars[k]);
            });
        }
        return s;
    }

    function apply() {
        document.documentElement.lang = lang === "en" ? "en" : "ru";
        document.querySelectorAll("[data-i18n]").forEach(function (el) {
            el.textContent = t(el.getAttribute("data-i18n"));
        });
        document.querySelectorAll("[data-i18n-placeholder]").forEach(function (el) {
            el.setAttribute("placeholder", t(el.getAttribute("data-i18n-placeholder")));
        });
        document.querySelectorAll("[data-i18n-aria]").forEach(function (el) {
            el.setAttribute("aria-label", t(el.getAttribute("data-i18n-aria")));
        });
        document.querySelectorAll("#position option").forEach(function (opt) {
            opt.textContent = t("pos_" + opt.value);
        });
        document.querySelectorAll(".lang-btn").forEach(function (btn) {
            btn.classList.toggle("on", btn.getAttribute("data-lang") === lang);
        });
    }

    function set(next) {
        lang = next === "en" ? "en" : "ru";
        localStorage.setItem("fc-lang", lang);
        apply();
        if (typeof window.onLangChange === "function") window.onLangChange();
    }

    document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll(".lang-btn").forEach(function (btn) {
            btn.addEventListener("click", function () {
                set(btn.getAttribute("data-lang"));
            });
        });
        apply();
    });

    return { t, apply, set, get: function () { return lang; } };
})();
window.Loc = Loc;
